# Example usage patterns for reusable workflows

# Pattern 1: Using secrets: inherit (RECOMMENDED)
# This automatically passes ALL secrets from the calling repository
name: CI/CD with Inherited Secrets
on:
  push:
    branches: [main]

jobs:
  test-and-lint:
    uses: joel-grant/github-actions/.github/workflows/test-lint-rails.yaml@main
    with:
      repo_name: my-rails-app
      ruby_version: '3.4.3'
      use_postgresql: true  # Default, can be omitted
    secrets: inherit  # No need to explicitly declare secrets!

  build:
    needs: test-and-lint
    uses: joel-grant/github-actions/.github/workflows/build-push.yaml@main
    secrets: inherit  # No need to explicitly declare secrets!

  deploy:
    needs: build
    uses: joel-grant/github-actions/.github/workflows/deploy.yaml@main
    with:
      environment: production
    secrets: inherit  # No need to explicitly declare secrets!

---

# Pattern 2: Explicit secrets
name: CI/CD with Explicit Secrets
on:
  push:
    branches: [main]

jobs:
  test-and-lint:
    uses: joel-grant/github-actions/.github/workflows/test-lint-rails.yaml@main
    with:
      repo_name: my-rails-app
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    needs: test-and-lint
    uses: joel-grant/github-actions/.github/workflows/build-push.yaml@main
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

---

# Pattern 3: Mixed approach (some inherited, some explicit)
name: CI/CD Mixed Approach
on:
  push:
    branches: [main]

jobs:
  test-and-lint:
    uses: joel-grant/github-actions/.github/workflows/test-lint-rails.yaml@main
    with:
      repo_name: my-rails-app
    secrets: inherit

  deploy-staging:
    uses: joel-grant/github-actions/.github/workflows/deploy.yaml@main
    with:
      environment: staging
    secrets:
      # Override specific secrets for staging environment
      kubeconfig: ${{ secrets.STAGING_KUBECONFIG }}
      kube_context: ${{ secrets.STAGING_CONTEXT }}
      # All other secrets inherited automatically
      inherit: true

---

# Pattern 4: Cache Control Examples
name: Cache Management Examples

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      bust_cache:
        description: 'Force rebuild without cache'
        required: false
        type: boolean
        default: false

jobs:
  # Normal build with cache
  build-cached:
    uses: joel-grant/github-actions/.github/workflows/build-push.yaml@main
    secrets: inherit

  # Build without cache (force rebuild)
  build-no-cache:
    if: github.event.inputs.bust_cache == 'true' || contains(github.event.head_commit.message, '[no-cache]')
    uses: joel-grant/github-actions/.github/workflows/build-push.yaml@main
    with:
      no_cache: true
    secrets: inherit

---

# Pattern 5: Rails Applications with Different Database Configurations
name: Rails Database Configurations

on:
  push:
    branches: [main]

jobs:
  # Rails app without database (API-only, background jobs, etc.)
  test-no-database:
    uses: joel-grant/github-actions/.github/workflows/test-lint-rails.yaml@main
    with:
      repo_name: my-api-app
      use_postgresql: false
    secrets: inherit

  # Rails app with PostgreSQL (default)
  test-with-postgresql:
    uses: joel-grant/github-actions/.github/workflows/test-lint-rails.yaml@main
    with:
      repo_name: my-web-app
      use_postgresql: true
      postgres_db: 'my_app_test'
      postgres_user: 'postgres'
      postgres_password: 'secret'
    secrets: inherit

  # Rails app with custom database URL (MySQL, SQLite, etc.)
  test-with-custom-db:
    uses: joel-grant/github-actions/.github/workflows/test-lint-rails.yaml@main
    with:
      repo_name: my-custom-app
      use_postgresql: false
      database_url: 'mysql2://user:password@localhost:3306/test_db'
    secrets: inherit

  # Rails app with external database service
  test-with-external-db:
    uses: joel-grant/github-actions/.github/workflows/test-lint-rails.yaml@main
    with:
      repo_name: my-cloud-app
      use_postgresql: false
      database_url: 'postgres://user:pass@external-db.example.com:5432/testdb'
    secrets: inherit
