# Workflow that uses the reusable build-push.yaml workflow
# This builds and pushes Docker images on push to main or manual trigger

name: Build and Push Docker Image

on:
  push:
    branches: 
      - main
  # Optional: Allow manual builds
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-push.yaml
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

# Alternative using secrets: inherit (passes ALL secrets automatically)
# jobs:
#   build-and-push:
#     uses: ./.github/workflows/build-push.yaml
#     secrets: inherit

# Example: Build on multiple triggers
# on:
#   push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:
#
# jobs:
#   build-and-push:
#     # Only push to registry on main branch, not PRs
#     if: github.ref == 'refs/heads/main'
#     uses: ./.github/workflows/build-push.yaml
#     secrets: inherit
