name: Test and Lint Rails
on:
  workflow_call:
    inputs:
      repo_name:
        description: 'Repository name for RubyCritic report URL'
        required: true
        type: string
      ruby_version:
        description: 'Ruby version to use (defaults to 3.4.3)'
        required: false
        type: string
        default: '3.4.3'
      postgres_db:
        description: 'PostgreSQL database name'
        required: false
        type: string
        default: 'rails_test'
      postgres_user:
        description: 'PostgreSQL username'
        required: false
        type: string
        default: 'rails'
      postgres_password:
        description: 'PostgreSQL password'
        required: false
        type: string
        default: 'password'
      skip_rubocop:
        description: 'Skip RuboCop linting'
        required: false
        type: boolean
        default: false
      skip_rubycritic:
        description: 'Skip RubyCritic'
        required: false
        type: boolean
        default: false
      use_postgresql:
        description: 'Enable PostgreSQL database service'
        required: false
        type: boolean
        default: true
      database_url:
        description: 'Custom database URL (overrides PostgreSQL settings)'
        required: false
        type: string
        default: ''
    secrets:
      dockerhub_username:
        description: 'DockerHub username'
        required: true
      dockerhub_token:
        description: 'DockerHub token'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: ${{ inputs.database_url != '' && inputs.database_url || (inputs.use_postgresql && format('postgres://{0}:{1}@localhost:5432/{2}', inputs.postgres_user, inputs.postgres_password, inputs.postgres_db) || '') }}
    services:
      postgres:
        image: ${{ inputs.use_postgresql && 'postgres:14.12-alpine' || '' }}
        ports:
          - ${{ inputs.use_postgresql && '5432:5432' || '' }}
        env:
          POSTGRES_DB: ${{ inputs.use_postgresql && inputs.postgres_db || '' }}
          POSTGRES_USER: ${{ inputs.use_postgresql && inputs.postgres_user || '' }}
          POSTGRES_PASSWORD: ${{ inputs.use_postgresql && inputs.postgres_password || '' }}
        options: ${{ inputs.use_postgresql && '--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5' || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.234.0
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true
      - name: Set up database schema
        if: ${{ inputs.use_postgresql || inputs.database_url != '' }}
        run: |
          if [ -f "bin/rails" ]; then
            bin/rails db:schema:load
          elif [ -f "bin/rake" ]; then
            bin/rake db:schema:load
          else
            bundle exec rails db:schema:load
          fi
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.234.0
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true
      - name: Resolve bundler with binstubs
        run: bundle binstubs bundler --force
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        if: ${{ !inputs.skip_rubocop }}
        run: bin/rubocop --parallel
    
  ruby-critic:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.234.0
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true
          
      - name: Fetch all branches
        run: git fetch

      - name: Run RubyCritic
        if: github.ref != 'refs/heads/main' && ${{ !inputs.skip_rubycritic }}
        run: |
          bundle exec rubycritic --mode-ci --no-browser

      - name: Upload RubyCritic report
        if: always() && github.ref != 'refs/heads/main' && ${{ !inputs.skip_rubycritic }}
        uses: actions/upload-artifact@v4
        with:
          name: rubycritic-report
          path: tmp/rubycritic

      - name: Deploy RubyCritic report to GitHub Pages
        if: always() && github.ref != 'refs/heads/main' && ${{ !inputs.skip_rubycritic }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tmp/rubycritic
          publish_branch: gh-pages
      
      - name: View Job Output
        if: always() && ${{ !inputs.skip_rubycritic }}
        run: |
          echo "View Report: https://joel-grant.github.io/${{ inputs.repo_name }}/compare/main/overview.html"